# Generated by Django 5.1.6 on 2025-03-27 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_transferenciaestoque'),
        ('suprimentos', '0009_alter_request_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciaestoque',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transferenciaestoque',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='transferenciaestoque',
            name='origem',
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='data_transferencia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='local_entrada',
            field=models.CharField(default='antigo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='local_saida',
            field=models.CharField(default='antigo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suprimentos.product'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
