# Generated by Django 5.1.6 on 2025-04-01 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_transferenciaestoque_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='data_saida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
