# Generated by Django 5.1.6 on 2025-04-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_saidaestoque_data_saida'),
        ('suprimentos', '0013_alter_request_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suprimentos.funcionario'),
        ),
    ]
