# Generated by Django 5.1.6 on 2025-04-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_saidaestoque_responsavel'),
        ('suprimentos', '0014_alter_request_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaestoque',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suprimentos.funcionario'),
        ),
    ]
