# Generated by Django 5.1.6 on 2025-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_transferenciaestoque_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
