# Generated by Django 5.2 on 2025-04-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_saidaestoque_observacao_and_more'),
        ('suprimentos', '0015_alter_request_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suprimentos.centrocusto'),
        ),
    ]
