# Generated by Django 5.2 on 2025-04-17 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_saidaestoque_centro_custo'),
        ('suprimentos', '0016_alter_request_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidaestoque',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suprimentos.centrocusto'),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='data_saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suprimentos.funcionario'),
        ),
    ]
