# Generated by Django 5.2 on 2025-04-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_saidaestoque_centro_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaestoque',
            name='funcionario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='tipo_entrada',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('DEVOLUCAO', 'Devolução')], default='COMPRA', max_length=10),
            preserve_default=False,
        ),
    ]
